Update deps

diff --git a/ClojureScript/replete/script/get-closure-compiler b/ClojureScript/replete/script/get-closure-compiler
--- a/ClojureScript/replete/script/get-closure-compiler
+++ b/ClojureScript/replete/script/get-closure-compiler
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
+
+if [ "${VERBOSE_BUILD:-0}" == "1" ]; then
+  set -x
+fi
+
 if [ ! -f compiler/closure-compiler-v$CLOSURE_RELEASE.jar ]; then
-  echo "Fetching Google Closure compiler..."
+  echo "Fetching Google Closure Compiler..."
   mkdir -p compiler
   cd compiler
-  curl --retry 3 -O -s https://dl.google.com/closure-compiler/compiler-$CLOSURE_RELEASE.zip || { echo "Download failed."; exit 1; }
-  unzip -qu compiler-$CLOSURE_RELEASE.zip
-  echo "Cleaning up Google Closure compiler archive..."
-  rm compiler-$CLOSURE_RELEASE.zip
+  curl --retry 3 -O -s https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v$CLOSURE_RELEASE/closure-compiler-v$CLOSURE_RELEASE.jar || { echo "Download failed."; exit 1; }
   cd ../..
 fi
